### ISSUE TITLE
m4v type video can't be downloaded

### ISSUE THREAD

**Issue by Akatsuki66peter** [Emy69/CoomerDL#10]
Will it support video downloads in m4v format in the future? Also can you provide an option to download all the attachments from the coomer website? Thanks
By the way, the best coomer downloader EVER!

**Comment by Emy69** [comment]
I forgot to add that video format, in the next update I add it
![image](https://github.com/Emy69/CoomerDL/assets/142945265/0d92269c-45bb-4ddb-8ece-69e9fc5995f6)
and in the part where you say about downloading from the coomer page do you mean that it works as a chrome extension something like that?

**Comment by Clementine66peter** [comment]
Thank you so much
and I mean there may also be some files in compressed file format like 'rar'/'zip'/'7z'.
Is this software likely to support downloads of these 'zip' files in the future?
