### ISSUE TITLE
Accesses far too frequently and gets error 429 too many requests

### ISSUE THREAD

**Issue by Orudeon** [Emy69/CoomerDL#12]
Yoooo, this program seems pretty nice and intuitive. Big problem though is I get Error 429 Client Error: Too Many Requests for url a hell of a lot. Probably to the point that it risks the user getting IP banned. I find that kemono, etc. tolerate up to three concurrent downloads, but two is safer.

**Comment by Emy69** [comment]
I'm still working on a solution, I hope to upload it in the next update. glad you like the program c:
