### ISSUE TITLE
add a file naming rule

### ISSUE THREAD

**Issue by daimaowangdemianbei** [Emy69/CoomerDL#15]
Could you pls add a file naming rule, the file names are not easy to manage now. Thanks bro!
naming rule:
`${titles[0]} ${index}_${pages}` // title 1_20.jpg     Example:   Yelan 1 Part 3 (Loop) 1_20.jpg

**Comment by Emy69** [comment]
I decided to make an option in the options menu for you to choose the one you prefer. 

![image](https://github.com/user-attachments/assets/f64543bf-3667-45c5-9e56-5d7ef4a276a9)

**Comment by daimaowangdemianbei** [comment]
thank you bro！
