### ISSUE TITLE
Only downloads the first page of videos

### ISSUE THREAD

**Issue by yeetcannon90** [Emy69/CoomerDL#18]
Hello, I'm noticing that it only downloads the first page of content. I am using V0.6.3 but had the same problem on 6.2.1.

If I point it to the link to the second page of content, it will download them - but ideally it would download all from that particular profile.

Example link (NSFW) - https://coomer.su/onlyfans/user/tsbritney (only downloads the first page of content)

Example link (NSFW) - https://coomer.su/onlyfans/user/tsbritney?o=50 (if pointed to this, it downloads the second page of content)

Thanks again for writing an awesome piece of software, it's very useful.

**Comment by Emy69** [comment]
![image](https://github.com/user-attachments/assets/3d25b988-8e38-4dc2-a0f2-0162ea2a3665)
just to check if you have this option activated?

**Comment by yeetcannon90** [comment]
> ![image](https://private-user-images.githubusercontent.com/142945265/373917887-3d25b988-8e38-4dc2-a0f2-0162ea2a3665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjIzMTksIm5iZiI6MTcyODIyMjAxOSwicGF0aCI6Ii8xNDI5NDUyNjUvMzczOTE3ODg3LTNkMjViOTg4LThlMzgtNGRjMi1hMGYyLTAxNjJlYTJhMzY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMzQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTU4NzJmOTQxMzM2NGI2MzhlZjVlOTg2YTAzMDlmNzI5YzMyYWEzY2YzNThkMWFmODI1NDE1YTMxNmRjMjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2IH2bx8hgWWSddXUsbB2FjzbiSd_TaT8E7LkqDaw5yo) just to check if you have this option activated?

That was it, my bad - I didn't realize that option was there. Apologies!!
