### ISSUE TITLE
Cant download anything

### ISSUE THREAD

**Issue by Meuserk** [Emy69/CoomerDL#25]
Hi I just startet using this but when i enter a URL and a folder i only get errors 
![image](https://github.com/user-attachments/assets/cf38623b-ffd5-4205-ad1a-5b83ae310ba1)

tis is the log to the picture "Total files downloaded: 0
Total images downloaded: 0
Total videos downloaded: 0
Errors: 1
Warnings: 0
Total download time: 0:00:00.100677

Files skipped because they were already downloaded:

Archivos fallidos:

Iniciando descarga...
Service extracted: onlyfans from site: coomer.su
Descargando post único...
Fetching user posts from https://coomer.su/api/v1/onlyfans/user/kittyxkum?o=0
Error fetching user posts: 404 Client Error: NOT FOUND for url: https://coomer.su/api/v1/onlyfans/user/kittyxkum?o=0
No post found for this ID.
All downloads completed or cancelled.
Logs successfully exported to resources\config\logs\log_20241126_171707.txt
Logs successfully exported to resources\config\logs\log_20241126_171707.txt
Iniciando descarga...
No se pudo extraer el ID del usuario.
URL no válida
Iniciando descarga...
Service extracted: onlyfans from site: coomer.su
Downloading all user content...
Starting download process...
Fetching user posts from https://coomer.su/api/v1/onlyfans/user/kittyxkum?o=0
Error fetching user posts: 404 Client Error: NOT FOUND for url: https://coomer.su/api/v1/onlyfans/user/kittyxkum?o=0
No posts found for this user.
All downloads completed or cancelled.
Logs successfully exported to resources\config\logs\log_20241126_171751.txt
"
how can i fix it?

**Comment by MachiavelliSeraphim** [comment]
Looks like the v1 api is either down or no longer in service.  It just dropped out about 2 hours ago and Cyberdrop-dl stopped functioning a day or 2 ago.  
https://coomer.su/api/v1/onlyfans/user/(any creator)?o=0 is coming back with {"error":"Not Found"}

**Comment by Emy69** [comment]
Coomer is making changes in the api, I already uploaded a version that solves it but they changed it again, I will wait a little bit until they stop making changes and I will modify the newest version.

**Comment by Emy69** [comment]
> Thanks. I was wondering if they were screwin around. Kinda funny to see I guessed right. I assume there will be a fresh build afterwards?

I'll wait for them to stop playing with the API, and in a few hours I'll upload a new one lol.

**Comment by Emy69** [comment]
I'm going to upload the solution on discord instead of github for now.
