### ISSUE TITLE
Add the option to download an entire profile

### ISSUE THREAD

**Issue by QuentinJ54** [Emy69/CoomerDL#26]
Hello, 
Could you please add the option to download an entire profile without having to go through each page one by one?
Thank you

**Comment by Emy69** [comment]
Hello, There is already a function implemented.

when it is not selected it says “Download only posts from the URL provided” and when selected it changes 
![image](https://github.com/user-attachments/assets/b281abad-0201-4324-8e8b-56c30de979dc)

**Comment by QuentinJ54** [comment]
Good morning,
Thank you, I hadn't seen it.
Sincerely
