### ISSUE TITLE
customtkinter Error

### ISSUE THREAD

**Issue by M4TZ3-op** [Emy69/CoomerDL#9]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from app.ui import ImageDownloaderApp
  File "/home/matze/Desktop/CoomerDL/app/ui.py", line 7, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'

**Comment by Emy69** [comment]
customtkinter depends on tkinter, so make sure that tkinter is properly installed before using customtkinter.

sudo apt-get install python3-tk

pip install customtkinter
